### ISSUE TITLE
无法选择调试的文件 scriptcat.target 命令不存在

### ISSUE THREAD

**Issue by bonaluo** [scriptscat/scriptcat-vscode#6]
我是通过onedrive同步到本地目录的，然后使用vscode打开同步到本地的目录，目录内有多个脚本，每次都会提示选择某个固定的脚本，想切换发现没有scriptcat.target命令

**Comment by bonaluo** [comment]
将文件单独复制到一个目录打开就可以，因为只有一个脚本可以选择

**Comment by CodFrm** [comment]
> 每次都会提示选择某个固定的脚本

是指的什么？

**Comment by CodFrm** [comment]
ctrl+p 输入`> scriptcat.targe` 即可

![b357bae3a2fe719a873b104713fbf755](https://github.com/user-attachments/assets/c9270bb5-8faa-4531-9383-c8635a05c516)

**Comment by bonaluo** [comment]
> ctrl+p 输入`> scriptcat.target` 即可
> 
> ![b357bae3a2fe719a873b104713fbf755](https://private-user-images.githubusercontent.com/22783163/348527157-c9270bb5-8faa-4531-9383-c8635a05c516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDU1MDAsIm5iZiI6MTcyMTIwNTIwMCwicGF0aCI6Ii8yMjc4MzE2My8zNDg1MjcxNTctYzkyNzBiYjUtOGZhYS00NTMxLTkzODMtYzg2MzVhMDVjNTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4MzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OGI5NjFjZDhkM2Y3YmNkYmFkYjgxZTA4YTFjM2ViMjU2N2YwNmNiZGZkMzY3OGRjODE0ODMwNTkxZTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rk6UgyccEpkzVH_M3FrxvNKiTXH-rpHyhmgq2JEM4PE)
但是我的命令栏没有这个功能，重新安装了好几次都不行
<img width="953" alt="image" src="https://github.com/user-attachments/assets/c991ae1d-01b3-449f-bad3-f10acdc6f507">
<img width="952" alt="image" src="https://github.com/user-attachments/assets/ea8e2df4-6014-40d5-9c36-91a55898f6a0">

**Comment by bonaluo** [comment]
> > ctrl+p 输入`> scriptcat.target` 即可
> > ![b357bae3a2fe719a873b104713fbf755](https://private-user-images.githubusercontent.com/22783163/348527157-c9270bb5-8faa-4531-9383-c8635a05c516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDU1MDAsIm5iZiI6MTcyMTIwNTIwMCwicGF0aCI6Ii8yMjc4MzE2My8zNDg1MjcxNTctYzkyNzBiYjUtOGZhYS00NTMxLTkzODMtYzg2MzVhMDVjNTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4MzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OGI5NjFjZDhkM2Y3YmNkYmFkYjgxZTA4YTFjM2ViMjU2N2YwNmNiZGZkMzY3OGRjODE0ODMwNTkxZTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rk6UgyccEpkzVH_M3FrxvNKiTXH-rpHyhmgq2JEM4PE)
> > 但是我的命令栏没有这个功能，重新安装了好几次都不行
> 
> <img alt="image" width="953" src="https://private-user-images.githubusercontent.com/27731323/349426310-c991ae1d-01b3-449f-bad3-f10acdc6f507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDU3NjgsIm5iZiI6MTcyMTIwNTQ2OCwicGF0aCI6Ii8yNzczMTMyMy8zNDk0MjYzMTAtYzk5MWFlMWQtMDFiMy00NDlmLWJhZDMtZjEwYWNkYzZmNTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4Mzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OGE2MWQ4OWE4NGNiMjMxYTlhMTgyMmQzZjI2ODM3ZDUwMjkyNjdkNmRmZjNiNWU4ODNhNzYyNTFlYmQwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laNzJIotqK9eNa7GXzU66a0rKmnU6hSh_tpLQvfpyek"> <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/27731323/349426450-ea8e2df4-6014-40d5-9c36-91a55898f6a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDU3NjgsIm5iZiI6MTcyMTIwNTQ2OCwicGF0aCI6Ii8yNzczMTMyMy8zNDk0MjY0NTAtZWE4ZTJkZjQtNjAxNC00MGQ1LTljMzYtOTFhNTU4OThmNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4Mzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMzBjODkzZDAyYzliMzc4YTg1ZWY4Y2NmZjQxMGZlZjdkM2ZkMjgzZDNhOGU2Nzg4MWNmOWEyN2IyZjU5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m-PIoYmfOVoJAaUGJ11argWjVj33-INaALW7iKIOV30">

原来要输入 `scriptcat.target` 全部才行🤣🤣🤣
